[custom]
# Executes when a game opens
start=omarchy-power-manager game

# Executes when a game closes (restore based on PS status)
end=bash -c 'if grep -q "1" /sys/class/power_supply/*/online; then omarchy-power-manager ac; else omarchy-power-manager bat; fi'
