# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = libinput-gestures
exec-once = solaar --window=hide
exec-once = uwsm app -- hyprsunset
exec-once = bash -c "sleep 5 && nautilus --gapplication-service"
exec-once = omarchy-mic-monitor
exec-once = omarchy-theme-set-keyboard && omarchy-brightness-keyboard restore

